Run the Phase 1.1 India validation workflow manually via this controlled trigger file. Do not edit this file except when an intentional live validation run is requested.
Trigger final India 300-session validation run after corporate-action parser QA fixes. Timestamp marker: 2026-10-02T21:31:00+05:30
