export const MAX_DAILY_BARS=320;
export const MAX_H4_BARS=180;
export function clean(v){return String(v??'').trim()}
export function num(v){const s=clean(v).replace(/,/g,'');if(!s||['-','NA','N/A','null'].includes(s))return null;const n=Number(s);return Number.isFinite(n)?n:null}
export function int(v){const n=num(v);return n==null?null:Math.trunc(n)}
export function normaliseDate(v){const s=clean(v);if(/^\d{4}-\d{2}-\d{2}$/.test(s))return s;let m=s.match(/^(\d{2})[\/-](\d{2})[\/-](\d{4})/);if(m)return `${m[3]}-${m[2]}-${m[1]}`;m=s.match(/^(\d{4})[\/-](\d{2})[\/-](\d{2})/);if(m)return `${m[1]}-${m[2]}-${m[3]}`;const d=new Date(s);return Number.isNaN(d.getTime())?null:d.toISOString().slice(0,10)}
export function upsertBars(existing,incoming,max=MAX_DAILY_BARS){const map=new Map();for(const b of existing||[])if(b?.date)map.set(b.date,b);for(const b of incoming||[])if(b?.date)map.set(b.date,b);return [...map.values()].sort((a,b)=>a.date.localeCompare(b.date)).slice(-max)}
export function ema(values,length){const out=Array(values.length).fill(null);if(length<=0)return out;let seed=0,count=0;const k=2/(length+1);for(let i=0;i<values.length;i++){const v=Number(values[i]);if(!Number.isFinite(v))continue;if(count<length){seed+=v;count++;if(count===length)out[i]=seed/length}else out[i]=v*k+(out[i-1]??v)*(1-k)}return out}
export function pctChange(values,lookback){if(values.length<=lookback)return null;const a=Number(values.at(-1)),b=Number(values.at(-1-lookback));if(!Number.isFinite(a)||!Number.isFinite(b)||b===0)return null;return (a/b-1)*100}
export function relativeStrength(stock,bench,lookback){const s=pctChange(stock,lookback),b=pctChange(bench,lookback);return s==null||b==null?null:s-b}
export function percentileRank(values,value){const xs=values.filter(Number.isFinite).sort((a,b)=>a-b);if(!xs.length||!Number.isFinite(value))return null;let below=0,equal=0;for(const x of xs){if(x<value)below++;else if(x===value)equal++;else break}const rank=(below+(equal?(equal-1)/2:0))/Math.max(1,xs.length-1)*100;return +rank.toFixed(2)}
export function buildDerived(stock,benchmark){const rows=(stock.daily||[]).filter(x=>x?.date&&Number.isFinite(Number(x.c)));const c=rows.map(x=>Number(x.c));const v=rows.map(x=>Number(x.v));const map=new Map((benchmark?.daily||[]).filter(x=>x?.date&&Number.isFinite(Number(x.c))).map(x=>[x.date,Number(x.c)]));const aligned=rows.filter(x=>map.has(x.date));const sAligned=aligned.map(x=>Number(x.c));const bAligned=aligned.map(x=>map.get(x.date));const e10=ema(c,10).at(-1)??null,e20=ema(c,20).at(-1)??null,e50=ema(c,50).at(-1)??null;const price=c.at(-1)??null;const h52=c.length?Math.max(...c.slice(-252)):null;const rs21=relativeStrength(sAligned,bAligned,21),rs55=relativeStrength(sAligned,bAligned,55),rs10w=relativeStrength(sAligned,bAligned,50);const vols=v.filter(Number.isFinite).slice(-20),avg=vols.length?vols.reduce((a,b)=>a+b,0)/vols.length:null;const rv20=avg&&Number.isFinite(v.at(-1))?v.at(-1)/avg:null;const pct20e=price!=null&&e20?100*(price/e20-1):null,pct50e=price!=null&&e50?100*(price/e50-1):null;const trend=price!=null&&e10!=null&&e20!=null&&e50!=null?(price>e10&&e10>=e20&&e20>=e50?'bull':price<e10&&e10<=e20&&e20<=e50?'bear':'mixed'):'unknown';return{price,ema10:e10,ema20:e20,ema50:e50,rs21,rs55,rs10w,pct20e,pct50e,rv20,h52,near52Pct:price!=null&&h52>0?100*(price/h52-1):null,trend,updated:rows.at(-1)?.date??null,rs_overlap_bars:aligned.length}}
export function compactStock(stock,benchmark){const daily=(stock.daily||[]).slice(-MAX_DAILY_BARS),h4=(stock.h4||[]).slice(-MAX_H4_BARS);return{sym:stock.ticker,nm:stock.name||stock.ticker,isin:stock.isin||null,series:stock.series||null,sector:null,industry:null,mc:null,c:daily.map(x=>x.c),v:daily.map(x=>x.v),del:daily.map(x=>x.delivery??null),c4:h4.map(x=>x.c),ohl:daily.slice(-20).map(x=>[x.o,x.h,x.l]),derived:buildDerived({daily},benchmark)}}
